config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_out", :to => "devise/sessions#destroy"
  end

  root to: "home#index"
  resources :users
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
          :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(auth)
    data = auth.info
    user = User.where(email: data["email"]).first

    unless user
        user = User.create(name: data["name"],
           email: data["email"],
           avatar_url: data["image"],
           provider: auth["provider"],
           uid: auth["uid"],
           password: Devise.friendly_token[0,20]
        )
    end

    if user.persisted?
      user.access_token = auth.credentials.token
      user.expires_at = auth.credentials.expires_at
      user.refresh_token = auth.credentials.refresh_token
      user.save!
    end

    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/google_calendar.rb
require "google/apis/calendar_v3"
require "google/api_client/client_secrets.rb"

module GoogleCalendar
  extend ActiveSupport::Concern
  def get_google_calendar_client(user)
    client = Google::Apis::CalendarV3::CalendarService.new
    return unless (user.present? && user.access_token.present? && user.refresh_token.present?)
    secrets = Google::APIClient::ClientSecrets.new({
      "web" => {
        "access_token" => user.access_token,
        "refresh_token" => user.refresh_token,
        "client_id" => ENV["GOOGLE_API_KEY"],
        "client_secret" => ENV["GOOGLE_API_SECRET"]
      }
    })
    begin
      client.authorization = secrets.to_authorization
      client.authorization.grant_type = "refresh_token"

      if !user.present?
        client.authorization.refresh!
        user.update_attributes(
          access_token: client.authorization.access_token,
          refresh_token: client.authorization.refresh_token,
          expires_at: client.authorization.expires_at.to_i
        )
      end
    rescue => e
      flash[:error] = "Your token has been expired. Please login again with google."
      redirect_to :back
    end
    client
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include GoogleCalendar
  before_action :authenticate_user!

  def index
    @events_list = get_events_list
  end

  private

  def get_events_list
    cache_key = "#{current_user.id}_events_list"
    events_list = Rails.cache.read(cache_key)
    return events_list if events_list

    client = get_google_calendar_client(current_user)
    calendar_id = "primary"
    response = client.list_events(calendar_id,
                               max_results:   10,
                               single_events: true,
                               order_by:      "startTime",
                               time_min:      DateTime.now.rfc3339)
    items = response.items.map do |event|
      start = event.start.date || event.start.date_time
      {
        start: start,
        summary: event.summary
      }
    end

    Rails.cache.write(cache_key, items, expires_in: 5.minute)
    items
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token

  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def map_alert_key(key)
    keys = {
      notice: "success",
      alert: "danger"
    }

    keys[key.to_sym] || key
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="p-3">
      <h3><%= current_user.email %>'s event</h3>
      <ul class="list-group">
        <% @events_list.each do |event| %>
          <li class="list-group-item d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
              <div class="fw-bold"><%= event[:summary] %></div>
            </div>
            <span class="badge bg-primary rounded-pill">
              <%= event[:start] %>
            </span>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="p-3 text-center">
  <% if user_signed_in? %>
    <h1>You're logged in! Welcome to the Dashboard!</h1>
    <h3>Signed user: <%= current_user.email %></h3>
    <%= link_to "View my events", events_path, class: "mb-3" %>
    <br/>
    <div class="mb-3">
    </div>
    <%= link_to "sign out", sign_out_path, class: "btn btn-danger" %>
  <% else %>
    <h2>You're Logged out! Log in to the Dashboard</h2>
    <%= link_to "sign in", sign_in_path, class: "btn btn-primary" %>
    <%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsGoogleAuth</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <% if flash.any? %>
        <% flash.each do |key, value| -%>
          <div class="alert alert-<%= map_alert_key(key) %>" role="alert">
            <%= value.html_safe %>
          </div>
        <% end -%>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>